package org.guardian;

public enum ActionType {

    BLOCK_BREAK, BLOCK_BURN, BLOCK_DISPENSE, BLOCK_FADE, BLOCK_FORM, BLOCK_FROM_TO,
    BLOCK_LAVA_FLOW, BLOCK_LAVA_FLOW_AS_PLAYER, BLOCK_WATER_FLOW, BLOCK_WATER_FLOW_AS_PLAYER,
    BLOCK_PLACE, BLOCK_SPREAD, BLOCK_SIGN_CHANGE, ENTITY_ENDERMEN_PICKUP, ENTITY_ENDERMEN_PLACE,
    ENTITY_CREEPER_EXPLODE, ENTITY_CREEPER_EXPLODE_AS_PLAYER, ENTITY_ENDERDRAGON_DESTROY,
    ENTITY_GHAST_FIREBALL, ENTITY_OTHER_EXPLODE, ENTITY_TNT_EXPLODE, ENTITY_PAINTING_BREAK,
    ENTITY_PAINTING_PLACE, INVENTORY_ADD, INVENTORY_CLICK, INVENTORY_TAKE, PLAYER_CHAT, PLAYER_COMMAND,
    PLAYER_BED_ENTER, PLAYER_BED_EXIT, PLAYER_BUCKET_EMPTY, PLAYER_BUCKET_FILL, PLAYER_DEATH,
    PLAYER_ITEM_DROP, PLAYER_INTERACT, PLAYER_JOIN, PLAYER_KICK, PLAYER_ITEM_PICKUP, PLAYER_TELEPORT,
    VEHICLE_CREATE, VEHICLE_DESTROY, VEHICLE_ENTER, VEHICLE_EXIT, WORLD_PORTAL_CREATE, WORLD_STRUCTURE_GROWM;
    public static int length = ActionType.values().length;

    public boolean isDefaultEnabled() {
        return true;
    }

    public String getConfigPath() {
        return toString().toLowerCase().replace('_', '-');
    }
}
